### ISSUE TITLE
自動販売機のデフォルト設定を行うBuilderクラスを生成する。

### ISSUE THREAD

**Issue by AtsushiOzawa** [AtsushiOzawa/tdd_vending-machine#35]
# 背景
- 自動販売機を使用するとき(=main.pyを書くとき)、自動販売機を生成 -> 飲み物の購入という流れになるが、自動販売機を生成する際に、インスタンス変数であるdrink_price、drink_boxの設定がやや煩雑である。
- この煩雑さをなくすために、以下を実行したい。
  - VendingMachineクラス内にcreate_defaultというクラスメソッドを準備
  - そのクラスメソッドはBuilderクラスを呼び出すよう設計。
  - 自動販売機の初期設定が完了。

**Comment by yamap55** [comment]
検討はしたものの、現在の実装では逆に冗長になる事が考えられるため一旦Closeとする。
必要になった場合には再度検討を行う。
