### ISSUE TITLE
drink_boxとvending_machine内のinfoで、drinkクラスを返すようにする。

### ISSUE THREAD

**Issue by AtsushiOzawa** [AtsushiOzawa/tdd_vending-machine#5]
# 背景
- vending_machineのget_inventoryメソッドでnameを返している。
- nameはあくまでdrinkの一部であり、drink自体を返した方が良いのではないか。

# 関連コード
[drink_box.py](https://github.com/AtsushiOzawa/tdd_vending-machine/blob/ae83df3bbb78cf965014d2ab8612f8d375de39b1/vending_machine/drink_box.py#L24..L36)
[vending_machine.py](https://github.com/AtsushiOzawa/tdd_vending-machine/blob/c3fb5f9a75efb20f7047e922d4e2ebefd5ca576c/vending_machine/vending_machine.py#L72..L81)

**Comment by yamap55** [comment]
対応済みなのでClose
